### ISSUE TITLE
Blacklight errors in logs when viewing Asset details page

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ams#576]
**Describe the bug**
I was tailing the log on production and seeing stack traces when viewing Asset details, even though the page renders.

**To Reproduce**
Just viewing an Asset details page results in the following stack trace in the log
```
F, [2021-05-12T21:09:54.397691 #2336] FATAL -- : [4edc3ce2-e1dc-43d3-b047-2c3956015ef3]   
F, [2021-05-12T21:09:54.397932 #2336] FATAL -- : [4edc3ce2-e1dc-43d3-b047-2c3956015ef3] Blacklight::Exceptions::RecordNotFound (Blacklight::Exceptions::RecordNotFound):
F, [2021-05-12T21:09:54.398073 #2336] FATAL -- : [4edc3ce2-e1dc-43d3-b047-2c3956015ef3]   
F, [2021-05-12T21:09:54.398244 #2336] FATAL -- : [4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/solr/repository.rb:14:in `find'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/app/models/concerns/blacklight/document/active_model_shim.rb:29:in `find'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/search_builders/hyrax/filter_suppressed_with_roles.rb:23:in `current_work'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/search_builders/hyrax/filter_suppressed_with_roles.rb:27:in `user_has_active_workflow_role?'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/search_builders/hyrax/filter_suppressed_with_roles.rb:16:in `only_active_works'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:147:in `block (2 levels) in processed_parameters'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:146:in `each'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:146:in `block in processed_parameters'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:145:in `tap'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:145:in `processed_parameters'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/search_builder.rb:119:in `to_hash'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/solr/repository.rb:61:in `block in send_and_receive'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/benchmarkable.rb:41:in `benchmark'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/solr/repository.rb:59:in `send_and_receive'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/lib/blacklight/solr/repository.rb:22:in `search'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/blacklight-6.23.0/app/controllers/concerns/blacklight/search_helper.rb:59:in `search_results'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/works_controller_behavior.rb:216:in `search_result_document'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/works_controller_behavior.rb:211:in `curation_concern_from_search_results'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/works_controller_behavior.rb:180:in `presenter'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/breadcrumbs_for_works.rb:38:in `add_breadcrumb_for_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/breadcrumbs.rb:26:in `trail_from_referer'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/breadcrumbs.rb:7:in `build_breadcrumbs'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/hyrax-2.9.0/app/controllers/concerns/hyrax/breadcrumbs_for_works.rb:18:in `build_breadcrumbs'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:106:in `block in run_callbacks'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:135:in `run_callbacks'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/active-fedora-12.1.1/lib/active_fedora/ldp_cache.rb:26:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/flipflop-2.6.0/lib/flipflop/feature_cache.rb:12:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] vendor/bundle/ruby/2.5.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/gems/ruby-2.5.3/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/gems/ruby-2.5.3/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/gems/ruby-2.5.3/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/gems/ruby-2.5.3/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[4edc3ce2-e1dc-43d3-b047-2c3956015ef3] /home/ec2-user/.rvm/gems/ruby-2.5.3/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Expected behavior**
No stack trace dumped.

### Done when
1. we discover the cause of the raised error
2. avoid raising it, or rescuing it

**Comment by singlesoliloquy** [comment]
This gem will go away. Tabling it.
